services:
  broker:
    image: redis:7.4.1-bookworm
    restart: unless-stopped
    networks:
      - phonemouse

  api:
    build: .
    ports:
      - "10000:10000"
    restart: unless-stopped
    depends_on:
      - broker
    networks: 
      - phonemouse
    environment:
      BROKER_HOST: broker
      BROKER_PORT: 6379
      BROKER_QUEUE: queue1

networks:
  phonemouse:
