services:
  broker:
    image: rabbitmq:3.13.7-alpine
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - phonemouse

  api:
    build: .
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - broker
    networks: 
      - phonemouse
    environment:
      BROKER_HOST: broker
      BROKER_PORT: 5672
      BROKER_QUEUE: queue1

networks:
  phonemouse:
